<<<<<<< HEAD
version: '3.5'

services:

  NagiosServer:
    image: jasonrivers/nagios
    ports:
     - 81:80
     
  db: #Postgres DB
    image: postgres:latest
    restart: always
    environment:
      POSTGRES_USER: zabbix
      POSTGRES_PASSWORD: zabbix
      POSTGRES_DB: zabbix
      PG_DATA: /var/lib/postgresql/data/pgdata

  zabbix-server:     # Servidor de coleta do Zabbix
    image: zabbix/zabbix-server-pgsql:ubuntu-latest
    restart: always
    environment:
      POSTGRES_USER: zabbix
      POSTGRES_PASSWORD: zabbix
      POSTGRES_DB: zabbix
      ZBX_HISTORYSTORAGETYPES: log,text
      ZBX_DEBUGLEVEL: 1
      ZBX_HOUSEKEEPINGFREQUENCY: 1
      ZBX_MAXHOUSEKEEPERDELETE: 5000
    depends_on:
      - db
    volumes:  
      - /usr/lib/zabbix/alertscripts:/usr/lib/zabbix/alertscripts
  
  zabbix-web:    # Interface WEB do ZABBIX encima do NGINX
    image: zabbix/zabbix-web-nginx-pgsql:ubuntu-latest
    restart: always
    environment:
      POSTGRES_USER: zabbix
      POSTGRES_PASSWORD: zabbix
      POSTGRES_DB: zabbix
      ZBX_SERVER_HOST: zabbix-server
      ZBX_POSTMAXSIZE: 64M
      PHP_TZ: "America/Sao_Paulo"  #Add São paulo
      ZBX_MAXEXECUTIONTIME: 500
    depends_on:
      - db
      - zabbix-server
    ports:    # Port where Zabbix UI is available
      - 8090:80

  zabbix-agent:   # Agente ddo zabbix
    image: zabbix/zabbix-agent:latest
    privileged: true
    network_mode: "host"
    restart: unless-stopped
    environment:
      - ZBX_SERVER_HOST=127.0.0.1

  adminer:  #Gerencia de databases
    image: adminer
    restart: always
    ports:
      - 8080:8080

  grafana-xxl:  #grafana (não configurado)
    image: monitoringartist/grafana-xxl:latest
    ports:
     - 3000:3000
=======
version: '3.1'

services:

  zabbixdb:
    image: monitoringartist/zabbix-db-mariadb:latest
    volumes:
      - /etc/localtime:/etc/localtime:ro
    environment:
      - MARIADB_USER=admin
      - MARIADB_PASS=admin

  zabbixserver:
    image: monitoringartist/dockbix-xxl:dev
    depends_on:
      - zabbixdb
    ports:
      - "80:80"
      - "10051:10051"
    volumes:
      - /etc/localtime:/etc/localtime:ro
    environment:
      - ZS_DBHost=zabbixdb
      - ZS_DBUser=admin
      - ZS_DBPassword=admin
      - XXL_zapix=true
      - XXL_grapher=true
      
  Nagios-Server:
    image: jasonrivers/nagios
    ports:
     - 0.0.0.0:8080:80
>>>>>>> e63dc1d6450f3b0703c7fb323e480951a1a386e1
